In [1]:
import numpy as np

In [138]:
class CNN:
    def __init__(self):
        pass

    def conv(self, image, kernal, featureMapShape,
             f=lambda x: x if(x > 0) else 0):
        if (featureMapShape):
            featureMap = np.zeros(featureMapShape)
            rng = featureMapShape[0]
        else:
            rng = int(len(image) - np.ceil(len(kernal)/2))
            featureMap = np.zeros((rng, rng))
        for i in range(rng):
            for j in range(rng):
                mbuff = image[j: j+len(kernal),
                              i: i+len(kernal)] * kernal 
                featureMap[j][i] = f(np.sum(mbuff))
        return featureMap
    
    def pooling(self, featureMap, box=3, stride=3, 
                f=lambda x:np.max(x)):
        rng = int((np.ceil(len(featureMap) / box)) * box)
        rng2 =int(rng/stride)
        pool = np.zeros((rng2, rng2))
        for i in range(rng2):
            for j in range(rng2):
                istride = i * stride
                jstride = j * stride
                pool[i][j] = f(featureMap[
                               istride: istride+box,
                               jstride: jstride+box])
        return pool
        
    def resizeImage(self, image, size, xbuff=0, ybuff=0):
        assert len(image) < size[0], "ERROR: resizeImage()"
        assert len(image[0]) < size[1], "ERROR: resizeImage()"
        canv = np.zeros(size)
        canv[ybuff:len(image)+ybuff,
             xbuff:len(image[0])+xbuff] += image
        return canv

In [141]:
print('Image')
image = np.array([[0,0,0,0,0,0,0],
                  [0,1,0,0,0,1,0],
                  [0,0,0,0,0,0,0],
                  [0,0,0,1,0,0,0],
                  [0,1,0,0,0,1,0],
                  [0,0,1,1,1,0,0],
                  [0,0,0,0,0,0,0]])
print(image)
print('Kernal')
kernal = np.array([[0,0,1],
                   [1,0,0],
                   [0,1,1]])
print(kernal)
cnn = CNN()
print('Feature Map')
featureMap = cnn.conv(image, kernal, (5,5))
print(featureMap)
print('Pooling')
pool = cnn.pooling(featureMap, 2, 2)
print(pool)

Image
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]]
Kernal
[[0 0 1]
 [1 0 0]
 [0 1 1]]
Feature Map
[[0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 2. 1.]
 [1. 4. 2. 1. 0.]
 [0. 0. 1. 2. 1.]]
Pooling
[[1. 1. 0.]
 [4. 2. 1.]
 [0. 2. 1.]]
